# Generated by Django 5.0.7 on 2024-08-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_is_superuser_alter_account_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
